### ISSUE TITLE
MongoDB fails to start

### ISSUE THREAD

**Issue by vvarga007** [microcks/microcks-operator#110]
### Describe the bug

MongoDB fails to run as it cannot create a lock file under /var/lib/mongodb/data.
A chown solved the problem, would it be worth adding it to the MongoDB deployment template?
Or an init container.
```yaml
lifecycle:
  postStart:
    exec:
      command:
        - /bin/sh
        - '-c'
        - chown mongodb:mongodb -R /var/lib/mongodb
```
