### ISSUE TITLE
Allow to configure AI Copilot OpenAI endpoint

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-operator#111]
### Reason/Context

As of today, the `OpenAICopilot` accepts an `api-url` configuration property to specify the API endpoint to use (default is https://api.openai.com/). However, setting a value to this property is not available when using the Operator for deployment.

### Description

We should allow a new `apiUrl` property (next to `apiKey`) in OpenAI configuration block of the `Microcks` Custom Resource:

```yaml
spec:
  features:
    # [...]
    # AI Copilot configuration properties
    aiCopilot:
      enabled: true
      implementation: openai

      openai:
        apiKey: <sk-my-openai-api-token>
        timeout: 20
        model: gpt-3.5-turbo
        maxTokens: 2000
```

### Implementation ideas

See above
