### ISSUE TITLE
Link to secret not preseved when using APISource

### ISSUE THREAD

**Issue by davidkarlsen** [microcks/microcks-operator#132]
### Describe the bug

I have this yaml:
```yaml
apiVersion: microcks.io/v1alpha1
kind: APISource
metadata:
  name: api-sources
  namespace: microcks-operator
  annotations:
    microcks.io/instance: microcks
  labels:
    dnb.no/ba: BSN0008349
spec:
  keepAPIOnDelete: false
  artifacts:
    # this one is for defining the mock responses
    - url: https://dev.azure.com/redacted/redacted/_apis/git/repositories/sre-refapp-domain-api/items?path=/refapp-domain-api-spec/src/main/resources/domain/microcks-examples.yaml
      mainArtifact: false
      secretRef: ado-repo-creds
  importers:
    - name: refapp-domain-api
      mainArtifact: true
      active: true
      # this is the one that defines the API
      repository:
        url: https://dev.azure.com/redacted/redacted/_apis/git/repositories/sre-refapp-domain-api/items?path=/refapp-domain-api-spec/src/main/resources/domain/customer-api-contract.yml
        secretRef: ado-repo-creds
      labels:
        team: sre
        project: refapp-domain-api

apiVersion: microcks.io/v1alpha1
kind: SecretSource
metadata:
  name: ado-repo-creds
  namespace: microcks-operator
  labels:
    dnb.no/ba: BSN0008349
  annotations:
    microcks.io/instance: microcks
spec:
  secrets:
  - name: ado-repo-creds
    description: 'ADO repo credentials for redacted project'
    valuesFrom:
      secretRef: ado-repo-creds
      passwordKey: password
      usernameKey: username

```

but when I go to the UI and do edit on the imported, the secret is not referenced.

I can edit the imported, select the secret from dropdown and save - and then import works.

### Expected behavior

secret-reference should be kept from k8s and no manual edit needed.

### Actual behavior

secret-ref is lost

### How to Reproduce?

See description

### Microcks version or git rev

1.11.2

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

operator
