### ISSUE TITLE
latest operator can't disable KC

### ISSUE THREAD

**Issue by davidkarlsen** [microcks/microcks-operator#146]
### Describe the bug

latest v0.4.0 operator will fail on 

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.23.0.1:443/apis/apps/v1/namespaces/microcks-operator/deployments/microcks?fieldManager=microcksreconciler&force=true. Message: failed to create typed patch object (microcks-operator/microcks; apps/v1, Kind=Deployment): .spec.template.spec.containers[name="spring"].env: duplicate entries for key [name="KEYCLOAK_ENABLED"]. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=failed to create typed patch object (microcks-operator/microcks; apps/v1, Kind=Deployment): .spec.template.spec.containers[name="spring"].env: duplicate entries for key [name="KEYCLOAK_ENABLED"], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
```

If I have a microcks of:
```
cat microcks.yaml
apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
  namespace: microcks-operator
spec:
  commonLabels:
    test: test
  #version: 1.11.2
  version: 1.12.0
  microcks:
    openshift:
      route:
        enabled: true
        tlsTermination: edge
    image:
      registry: npeprodcontainerregistry.azurecr.io/quay.io
    env:
      - name: KEYCLOAK_ENABLED
        value: 'false'
  postman:
    image:
      registry: npeprodcontainerregistry.azurecr.io/quay.io
  keycloak:
    install: false
    persistent: true
    volumeSize: 1Gi
    url: 'fake'
  mongodb:
    image:
      registry: npeprodcontainerregistry.azurecr.io/docker.io
    install: true
    persistent: true
    volumeSize: 2Gi
  features:
    async:
      enabled: false
```

**Comment by lbroudoux** [comment]
Hello,

Thanks for opening this issue. In fact, since the release of https://github.com/microcks/microcks-operator/issues/120, there's a cleaner way to disable Keycloak that should now be used. You can do so by adapting your CR to:

```yaml
apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
  namespace: microcks-operator
spec:
  commonLabels:
    test: test
  version: 1.12.0
  microcks:
    openshift:
      route:
        enabled: true
        tlsTermination: edge
  keycloak:
    enabled: false
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi
  features:
    async:
      enabled: false
```

So just put `spec.keycloak.enabled=false` should do the trick.

That said, we shouldn't fail that hard in the case you mention, especially when migrating from a previous version of the operator. I'm gonna check and see if you could avoid that exception.
