### ISSUE TITLE
Add ability to add common labels and annotations to all the created resources

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-operator#32]
### Reason/Context

See https://github.com/microcks/microcks/issues/1005

### Description

Add the ability to manage:

```yaml
spec:
  version: '1.10.0'
  commonLabels:
    foo: bar
  commonAnnotations
    bar: baz
```

to propagate labels and annotations to all the resources created by this operator.
