### ISSUE TITLE
Add Image specification to different components

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-operator#43]
### Reason/Context

While working on #41, I realized we hadn't introduced image specification capability for components yet. Having the ability to specify images coordinates for each component is foundational.

### Description

We should align on latest Helm chart improvements that allows specifying images using this kind of block:

```yaml
keycloak:
  image:
    registry: quay.io
    repository: keycloak/keycloak
    tag: 24.0.4
    digest: 
```

If `sha 256` digest is provided, it takes precedence on `tag` specification to allow pinning images.
